### ISSUE TITLE
Merging

### ISSUE THREAD

**Issue by abellc16** [ECU-CSCI-4230/SpiralBound#18]
When attempting to merge FlashCards into demo, it did not work. 

I think I am going to 'merge' manually. It will be a pain and incorrect, but it will probably work just fine.

**Comment by KuraideWolfie** [comment]
The `Notebook-GUI` branch, and then the `FlashCards` branch, were merged into the `master` branch. Resolution of errors caused by the merge of FlashCards was handled, and a commit atop the merge present that fixes the issues. _(Testing was also performed to ensure the GUI operates as expected after merging.)_

- [ ] `FlashCards_ImportTool` and `demo` should be deleted
- [ ] `Notebook-GUI` and `FlashCards` should be rebased on the master branch

**Comment by KuraideWolfie** [comment]
`Notebook-GUI` has been rebased on the master branch.

**Comment by abellc16** [comment]
I deleted both the demo branch and the importTool branch

**Comment by KuraideWolfie** [comment]
Closing this issue because of the fact that both FlashCards and Notebook-GUI were updated during a meeting on Tuesday.
