### ISSUE TITLE
New Notebook Interface

### ISSUE THREAD

**Issue by KuraideWolfie** [ECU-CSCI-4230/SpiralBound#28]
**Ketu**: Create a new ui window, allowing the entry of the name and author of a notebook. _(The date should be auto-generated on the creation of the UI window.)_ **Matt**: This interface should then be linked to a 'new' entry under File.

- If the current notebook isn't saved, prompt to save
- If the current notebook is saved, make a new book
- Remember to properly reset the flash cards and calendar
- Only characters in A-Z, a-z, 0-9, -, and _ should be allowed for notebook names

**Comment by KuraideWolfie** [comment]
I'm removing myself from this issue to work on the import window. @Kets1596, you will be responsible for making this new interface window work.

**Comment by Kets1596** [comment]
There are several things related to the backend that needs to be finished. 
Upon adding a new book:
(1). If the  "book name" provided by user already exists in the directory, then the user will be provided with a prompt asking if he would like to overwrite it. 
      * If "Yes", The code needs to be added to overwrite the book. 
      * if "No", everything should be left as it is!! 

(3) If the "book name" does not exist in the directory, process to create a new notebook.
      * we have to reset calendar, flash cards and set up a new notebook. The code for this also needs to be implemented. 
(4) You may also have to look at receivedBookData function in mainwindow and tie the received data with the backend.  

Since you are more familiar with the backend stuff, see if you can help with it. @KuraideWolfie

**Comment by KuraideWolfie** [comment]
The processing for creating a new book was completed; however, for overwrite, nothing is saved if the user confirms. To truly overwrite the book, the user will have to save after creating the notebook. Further features were added, such as prompting about unsaved changes (the most recent commit will reflect this). Unsaved changes are regarded as:
- Adding, removing, or editing sections and pages
- Typing new notes into the plainTextEdit field
- Adding, removing, and editing calendar events
- _(On completion of ST-Revamp)_ Adding, editing, removing decks or cards
